package com.dmitrievanthony.clist;

import java.util.Iterator;
import java.util.stream.Stream;

/**
 * Tests for <tt>ByteCompactList</tt> generated by {@link CompactListGenerator} and {@link CompactListFactory}.
 */
public class ByteCompactListTest extends CompactListAbstractTest<Byte> {
    /** {@inheritDoc} */
    @Override
    Iterator<Byte> getSequence() {
        return Stream.iterate((byte)0, e -> (byte)(e + 1)).iterator();
    }

    /** {@inheritDoc} */
    @Override
    CompactList<Byte> getCompactList() {
        return new CompactListFactory().newCompactList(Byte.class);
    }
}
