package com.dmitrievanthony.clist;

import java.util.Iterator;
import java.util.stream.Stream;

/**
 * Tests for <tt>CharacterCompactList</tt> generated by {@link CompactListGenerator} and {@link CompactListFactory}.
 */
public class CharacterCompactListTest extends CompactListAbstractTest<Character> {
    /** {@inheritDoc} */
    @Override
    Iterator<Character> getSequence() {
        return Stream.iterate((char)0, e -> (char)(e + 1)).iterator();
    }

    /** {@inheritDoc} */
    @Override
    CompactList<Character> getCompactList() {
        return new CompactListFactory().newCompactList(Character.class);
    }
}
