package com.dmitrievanthony.clist;

import java.util.Iterator;
import java.util.stream.Stream;

/**
 * Tests for <tt>DoubleCompactList</tt> generated by {@link CompactListGenerator} and {@link CompactListFactory}.
 */
public class DoubleCompactListTest extends CompactListAbstractTest<Double> {
    /** {@inheritDoc} */
    @Override
    Iterator<Double> getSequence() {
        return Stream.iterate(0d, e -> e + 1).iterator();
    }

    /** {@inheritDoc} */
    @Override
    CompactList<Double> getCompactList() {
        return new CompactListFactory().newCompactList(Double.class);
    }
}
