package com.dmitrievanthony.clist;

import java.util.Iterator;
import java.util.stream.Stream;

/**
 * Tests for <tt>LongCompactList</tt> generated by {@link CompactListGenerator} and {@link CompactListFactory}.
 */
public class LongCompactListTest extends CompactListAbstractTest<Long> {
    /** {@inheritDoc} */
    @Override
    Iterator<Long> getSequence() {
        return Stream.iterate(0L, i -> i + 1).iterator();
    }

    /** {@inheritDoc} */
    @Override
    CompactList<Long> getCompactList() {
        return new CompactListFactory().newCompactList(Long.class);
    }
}
