package com.dmitrievanthony.clist;

import java.util.Iterator;
import java.util.stream.Stream;

/**
 * Tests for <tt>ShortCompactList</tt> generated by {@link CompactListGenerator} and {@link CompactListFactory}.
 */
public class ShortCompactListTest extends CompactListAbstractTest<Short> {
    /** {@inheritDoc} */
    @Override
    Iterator<Short> getSequence() {
        return Stream.iterate((short)0, e -> (short)(e + 1)).iterator();
    }

    /** {@inheritDoc} */
    @Override
    CompactList<Short> getCompactList() {
        return new CompactListFactory().newCompactList(Short.class);
    }
}
